import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function MessageLog({ messages, onSendMessage }) {
    const [filter, setFilter] = useState('all');
    const filtered = messages.filter((m) => (filter === 'all' ? true : m.direction === filter));
    return (_jsxs("div", { className: "glass-card rounded-2xl p-6 animate-fade-in delay-100", children: [_jsxs("div", { className: "flex items-center justify-between mb-6 flex-wrap gap-3", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-bold text-slate-900", children: "Live Message Log" }), _jsx("p", { className: "text-sm text-slate-500", children: "Real-time incoming and outgoing messages" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "flex rounded-lg border border-slate-200 overflow-hidden", children: ['all', 'incoming', 'outgoing'].map((f) => (_jsx("button", { onClick: () => setFilter(f), className: `px-3 py-1.5 text-xs font-medium capitalize transition-colors ${filter === f
                                        ? 'bg-slate-800 text-white'
                                        : 'bg-white text-slate-500 hover:bg-slate-50'}`, children: f }, f))) }), _jsxs("button", { onClick: onSendMessage, className: "text-orange-600 bg-orange-50 px-4 py-2.5 rounded-xl text-sm font-semibold hover:bg-orange-100 transition-all flex items-center gap-2", children: [_jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 19l9 2-9-18-9 18 9-2zm0 0v-8" }) }), "Quick Send"] })] })] }), _jsx("div", { className: "overflow-hidden rounded-xl border border-slate-200", children: _jsxs("table", { className: "min-w-full text-sm", children: [_jsx("thead", { className: "bg-slate-50/80 backdrop-blur text-slate-500 font-medium", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left", children: "Time" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Direction" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Details" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Message" })] }) }), _jsxs("tbody", { className: "divide-y divide-slate-100 bg-white", children: [filtered.map((msg) => (_jsxs("tr", { className: "hover:bg-slate-50/80 transition-colors group", children: [_jsx("td", { className: "px-4 py-3 whitespace-nowrap text-slate-400 font-mono text-xs", children: new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) }), _jsx("td", { className: "px-4 py-3 whitespace-nowrap", children: _jsx("span", { className: `px-2 py-1 rounded text-xs font-bold uppercase tracking-wider ${msg.direction === 'incoming' ? 'bg-blue-50 text-blue-600' : 'bg-orange-50 text-orange-600'}`, children: msg.direction === 'incoming' ? 'Incoming' : 'Outgoing' }) }), _jsxs("td", { className: "px-4 py-3", children: [_jsx("div", { className: "text-xs font-medium text-slate-900", children: msg.from || msg.to }), _jsx("div", { className: "text-[10px] text-slate-400 font-mono", children: msg.sessionId })] }), _jsx("td", { className: "px-4 py-3", children: _jsx("p", { className: "text-slate-700 line-clamp-2 max-w-sm", children: msg.text }) })] }, msg.id))), filtered.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 4, className: "px-4 py-8 text-center text-slate-400 text-sm", children: messages.length === 0 ? 'Waiting for messages...' : 'No messages match this filter.' }) }))] })] }) })] }));
}
